ARG VERSION
FROM almalinux:${VERSION:-9}
#indise condtainer
ARG COURSE="DOCKER" \
 TRAINER="SIVAKUMAR"
 RUN echo "Trainer:  ${TRAINER} , COURSE: ${COURSE} , Verssion: ${VERSION} "
 CMD [ "sleep" ,"1000" ]

