ARG VERSION
FROM almalinux:${VERSION:-9}
#indise condtainer
ARG COURSE="DOCKER" \
 TRAINER="SIVAKUMAR"
 RUN echo "Trainer:  ${TRAINER} , COURSE: ${COURSE} , Verssion: ${VERSION} "
 #[2/2] RUN echo "Trainer:  SIVAKUMAR , COURSE: DOCKER , Verssion: ${VERSION} "        
 #after from  arg  will not work befor from arg will work
 
 CMD [ "sleep" ,"1000" ]

